### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by fmendoza** [D1ceWard/plausible_on_dokku#1]
I'm trying to set up a plausible instance and I would like to manage it via Dokku.

Is this plugin already working? If so, are there documentation or a blog post to check?

Happy to help if you need a hand.

**Comment by D1ceWard** [comment]
I changed my approach (dokku app instead of dokku plugin) and added setup guide.
I successfully deployed it on my dokku instance and started using it. (Everything work fine)
So feel free to follow the guide and ask for clarification or improvements by creating issue in case of problem or missing elements.

**Comment by fmendoza** [comment]
thanks for sharing the setup guide @D1ceWard I will give it a try.
